version '2.1'

services:
 app: 
   container_name: docker-node-mongo
   restart: always
   build: .
   ports:
    - '80:5000'
  links:
    - db
 db: 
  container_name: mongo
  image: mongo
  ports: 
    - '27017:27017'

   
  